# -*- coding: latin-1 -*-
# generated by wxGlade 0.6.3 on Tue May 29 17:29:47 2012

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

from graph_elem import *
import time


class TicFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Trace.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook = wx.Notebook(self, -1, style=0)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        
        self.__planches = []

    def __set_properties(self):
        # begin wxGlade: Trace.__set_properties
        self.SetTitle("pyTicTac")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Trace.__do_layout
        main_sizer = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        main_sizer.Add(self.notebook, 1, wx.EXPAND, 0)
        self.SetSizer(main_sizer)
        main_sizer.Fit(self)
        self.Layout()
        # end wxGlade
        
    def creerPlanche(self, titre):
        pl = Planche(self.notebook, -1, name=titre)
        self.notebook.AddPage(pl,titre)
        self.__planches.append(pl)
        return pl
        
    def trace(self):
        for pl in self.__planches:
            pl.trace()

# end of class Trace

class Fenetre(wx.PySimpleApp):
   def OnInit(self):
      self.frame = TicFrame(None, -1, "pyApple")
      self.frame.Show(True)
      self.SetTopWindow(self.frame)
      
      self.keepGoing = True
      
      return True
   
   def creerPlanche(self, titre):
      return self.frame.creerPlanche(titre)
      
   def afficher(self):
      # Calcul du rendu de courbe
      self.frame.trace()
      
      self.frame.Maximize()
      self.MainLoop()
      




