name: Trigger Jenkins checks

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Jenkins checks
      run: |
        curl http://admin:${{ secrets.jenkins_password }}@94.23.18.179:8080/job/github.ydethe.SystemControl/build\?token\=isolated-joyfully-borrowing
