# https://github.com/actions/starter-workflows/blob/master/ci/python-publish.yml


name: Upload Python Package

on:
  push:
    tags:
    - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish on pypi.org
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
    - name: Build doc and publish on readthedocs.org
      run: |
          curl -d "" -X POST -H "Authorization: Token ${{ secrets.rtd_token}}" https://readthedocs.org/api/v3/projects/pyapple/versions/latest/builds/
